feat: 1.0.0 (#49)
* fix: bump actions/checkout from 4.1.7 to 4.2.0 (#44)

Bumps [actions/checkout](https://github.com/actions/checkout) from 4.1.7 to 4.2.0.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v4.1.7...v4.2.0)

---
updated-dependencies:
- dependency-name: actions/checkout
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix: bump bandit[toml] from 1.7.9 to 1.7.10 (#43)

Bumps [bandit[toml]](https://github.com/PyCQA/bandit) from 1.7.9 to 1.7.10.
- [Release notes](https://github.com/PyCQA/bandit/releases)
- [Commits](https://github.com/PyCQA/bandit/compare/1.7.9...1.7.10)

---
updated-dependencies:
- dependency-name: bandit[toml]
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix: bump pylint from 3.3.0 to 3.3.1 (#42)

Bumps [pylint](https://github.com/pylint-dev/pylint) from 3.3.0 to 3.3.1.
- [Release notes](https://github.com/pylint-dev/pylint/releases)
- [Commits](https://github.com/pylint-dev/pylint/compare/v3.3.0...v3.3.1)

---
updated-dependencies:
- dependency-name: pylint
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* feat: update workflows to have rules (#45)

* added documentation (#46)

* doc: doc version from odsbox (#47)

* feat: set version to 1.0.0 (#48)

* fix linter

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/semantic-pr-check.yml b/.github/workflows/semantic-pr-check.yml
--- a/.github/workflows/semantic-pr-check.yml
+++ b/.github/workflows/semantic-pr-check.yml
@@ -15,3 +15,16 @@ jobs:
       - uses: amannn/action-semantic-pull-request@v5.5.3
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  restrict-merge:
+    name: Restrict PR to main to dev and hotfix/*
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check source branch
+      if: github.event.pull_request.base.ref == 'main'
+      run: |
+        if [[ "${{ github.event.pull_request.head.ref }}" =~ ^(dev|hotfix/.*|release/.*)$ ]]; then
+          echo "Branch name is valid."
+        else
+          echo "Invalid branch name. Only 'dev' or 'hotfix/*' branches can be merged into 'main'."
+          exit 1
+        fi
